spring.application.name=uv-move-backend
server.port=8080

# Configuración IBM Db2
spring.datasource.url=jdbc:db2://localhost:50000/uvmove
spring.datasource.username=db2inst1
spring.datasource.password=uvmovepass
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuración JWT de Supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://surwvkpzpnbrnkhynbkx.supabase.co/auth/v1
