--SCRIPT IBM DB2 HOMOLOGADO
-- 1. Tabla de Usuarios
CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(50) NOT NULL PRIMARY KEY,
    ESTATUS_ACTIVO BOOLEAN NOT NULL
);

-- 2. Tabla del Gestor de Flota
CREATE TABLE FLOTA_VEHICULOS (
    ID_VEHICULO VARCHAR(10) NOT NULL PRIMARY KEY,
    TIPO_VEHICULO VARCHAR(20) NOT NULL,
    ESTADO_FISICO VARCHAR(20) NOT NULL,
    NIVEL_BATERIA INT,
    LATITUD DECIMAL(9,6),
    LONGITUD DECIMAL(9,6)
);

-- 3. Tabla del Gestor de Viajes 
CREATE TABLE VIAJES_REGISTRO (
    ID_VIAJE INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    ID_USUARIO VARCHAR(50) NOT NULL,
    ID_VEHICULO VARCHAR(10) NOT NULL,
    HORA_INICIO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
    HORA_FIN TIMESTAMP,
    ESTADO_VIAJE VARCHAR(15) NOT NULL,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES FLOTA_VEHICULOS(ID_VEHICULO)
);

-- 4. Datos de Prueba 

-- Usuarios
INSERT INTO USUARIO (ID_USUARIO, ESTATUS_ACTIVO) VALUES ('S20012345', TRUE);
INSERT INTO USUARIO (ID_USUARIO, ESTATUS_ACTIVO) VALUES ('S20012346', FALSE);

-- Vehículo disponible
INSERT INTO FLOTA_VEHICULOS (ID_VEHICULO, TIPO_VEHICULO, ESTADO_FISICO, NIVEL_BATERIA, LATITUD, LONGITUD) 
VALUES ('B-001', 'Bicicleta', 'Disponible', 100, 19.5432, -96.9123);

-- Vehículo averiado 
INSERT INTO FLOTA_VEHICULOS (ID_VEHICULO, TIPO_VEHICULO, ESTADO_FISICO, NIVEL_BATERIA, LATITUD, LONGITUD) 
VALUES ('B-002', 'Scooter', 'Mantenimiento', 15, 19.5445, -96.9111);

-- Vehículo extra en uso
INSERT INTO FLOTA_VEHICULOS (ID_VEHICULO, TIPO_VEHICULO, ESTADO_FISICO, NIVEL_BATERIA, LATITUD, LONGITUD) 
VALUES ('B-003', 'Bicicleta', 'En uso', 80, 19.5450, -96.9100);
